version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://db_admin:$ec8re_pa55c0de@shlaiman_db:5432/postgres
    depends_on:
      - shlaiman_db

  shlaiman_db:
    image: postgres:12
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: $ec8re_pa55c0de
