"""added user notes and meeting_point db

Revision ID: 5aa18e39da4b
Revises: 2b6ba58913a2
Create Date: 2024-05-31 13:51:50.305988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa18e39da4b'
down_revision = '2b6ba58913a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_point', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
