"""Add passcode to group model

Revision ID: bee0d823621a
Revises: da1ef278d52d
Create Date: 2024-05-29 21:13:53.587841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee0d823621a'
down_revision = 'da1ef278d52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('passcode',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('passcode_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('passcode_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('passcode',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###
