"""added user notes and meeting_point db

Revision ID: fca44b8c0d1b
Revises: b3489b0e8e79
Create Date: 2024-05-31 12:29:43.335674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca44b8c0d1b'
down_revision = 'b3489b0e8e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_point', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('note')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
